<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RootNamespace>HamedSoft.Template.Application</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Features\Commands\Auth\Logout\**" />
	  <EmbeddedResource Remove="Features\Commands\Auth\Logout\**" />
	  <None Remove="Features\Commands\Auth\Logout\**" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\HamedSoft.Template.Domain\HamedSoft.Template.Domain.csproj" />
		<ProjectReference Include="..\HamedSoft.Template.SharedKernel\HamedSoft.Template.SharedKernel.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="FluentValidation" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
		<PackageReference Include="MediatR" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Features\Commands\Register\" />
	</ItemGroup>

</Project>
