<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RootNamespace>HamedSoft.Template.Application</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\HamedSoft.Template.Domain\HamedSoft.Template.Domain.csproj" />
		<ProjectReference Include="..\HamedSoft.Template.SharedKernel\HamedSoft.Template.SharedKernel.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="FluentValidation" />
		<PackageReference Include="MediatR" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Features\Auth\Logout\" />
	  <Folder Include="Features\Auth\Register\" />
	  <Folder Include="Behaviors\" />
	</ItemGroup>

</Project>
