<Project Sdk="Microsoft.NET.Sdk">
	
	<PropertyGroup>
		<RootNamespace>HamedSoft.Template.Infrastructure</RootNamespace>
	</PropertyGroup>
	
	<ItemGroup>
	  <Compile Remove="Repositories\**" />
	  <EmbeddedResource Remove="Repositories\**" />
	  <None Remove="Repositories\**" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\HamedSoft.Template.Application\HamedSoft.Template.Application.csproj" />
		<ProjectReference Include="..\HamedSoft.Template.Domain\HamedSoft.Template.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="MediatR" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>
				runtime; build; native; contentfiles; analyzers; buildtransitive
			</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Persistence\Migrations\" />
	</ItemGroup>

</Project>
